#!/bin/sh

set -e

for py in $(py3versions -s); do
    echo "[*] testing $py:"
    lib=$($py -c 'from distutils import sysconfig; print(sysconfig.get_python_lib())')
    /usr/bin/zope-testrunner3 -k -vv --test-path ${lib} -s zope.testing
done
